 * Serving Flask app "lib" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
 * Debugger is active!
 * Debugger PIN: 186-544-833
127.0.0.1 - - [20/Sep/2018 17:58:36] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 17:58:36] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:03:36] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:03:36] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:08:35] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:08:36] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:13:35] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:13:36] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:18:35] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:18:36] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:23:35] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:23:36] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:28:35] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:33:35] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [20/Sep/2018 18:38:35] "POST / HTTP/1.1" 405 -
 * Serving Flask app "lib" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
 * Debugger is active!
 * Debugger PIN: 186-544-833
127.0.0.1 - - [25/Sep/2018 16:40:31] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [25/Sep/2018 16:40:32] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [25/Sep/2018 16:40:41] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [25/Sep/2018 16:40:41] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [25/Sep/2018 16:40:51] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [25/Sep/2018 16:40:51] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [25/Sep/2018 16:41:01] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [25/Sep/2018 16:41:01] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [25/Sep/2018 16:41:11] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [25/Sep/2018 16:41:11] "POST / HTTP/1.1" 405 -
127.0.0.1 - - [25/Sep/2018 16:42:34] "POST /api/place HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/views/api.py", line 15, in save_visited_place
    place_model.detect_place(user_id)
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/models/places.py", line 22, in detect_place
    prev_location.longitude
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/util/geo.py", line 22, in cal_rho
    c2=(sin(xx)+xx)*(sin(pa)-sin(pb))**2/sin(xx/2)**2
ZeroDivisionError: float division by zero
127.0.0.1 - - [25/Sep/2018 16:42:34] "POST /api/place HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/views/api.py", line 15, in save_visited_place
    place_model.detect_place(user_id)
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/models/places.py", line 22, in detect_place
    prev_location.longitude
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/util/geo.py", line 22, in cal_rho
    c2=(sin(xx)+xx)*(sin(pa)-sin(pb))**2/sin(xx/2)**2
ZeroDivisionError: float division by zero
127.0.0.1 - - [25/Sep/2018 16:42:44] "POST /api/place HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/views/api.py", line 15, in save_visited_place
    place_model.detect_place(user_id)
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/models/places.py", line 22, in detect_place
    prev_location.longitude
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/util/geo.py", line 22, in cal_rho
    c2=(sin(xx)+xx)*(sin(pa)-sin(pb))**2/sin(xx/2)**2
ZeroDivisionError: float division by zero
127.0.0.1 - - [25/Sep/2018 16:42:44] "POST /api/place HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/views/api.py", line 15, in save_visited_place
    place_model.detect_place(user_id)
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/models/places.py", line 22, in detect_place
    prev_location.longitude
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/util/geo.py", line 22, in cal_rho
    c2=(sin(xx)+xx)*(sin(pa)-sin(pb))**2/sin(xx/2)**2
ZeroDivisionError: float division by zero
127.0.0.1 - - [25/Sep/2018 16:42:54] "POST /api/place HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/views/api.py", line 15, in save_visited_place
    place_model.detect_place(user_id)
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/models/places.py", line 22, in detect_place
    prev_location.longitude
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/util/geo.py", line 22, in cal_rho
    c2=(sin(xx)+xx)*(sin(pa)-sin(pb))**2/sin(xx/2)**2
ZeroDivisionError: float division by zero
127.0.0.1 - - [25/Sep/2018 16:42:54] "POST /api/place HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maruyama/.local/share/virtualenvs/GraduationResearch-GNPcCtFM/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/views/api.py", line 15, in save_visited_place
    place_model.detect_place(user_id)
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/models/places.py", line 22, in detect_place
    prev_location.longitude
  File "/Users/maruyama/Documents/Study/GraduationResearch/lib/util/geo.py", line 22, in cal_rho
    c2=(sin(xx)+xx)*(sin(pa)-sin(pb))**2/sin(xx/2)**2
ZeroDivisionError: float division by zero
